# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3x" do
  version "0.3.8"

  on_macos do
    on_arm do
      sha256 "3e78d96005a40abc6a5b4253970543b2cb6a8bafed0432415873af3e711008fa"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a0a9d41ed20ff18cc2d1b1aff4b3e9960dadabe8f84a61244f6c2fa2d33d5b1"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aee5a2286e206d5dd714bdae6bfa6c24e00e72033ef85e86be4e88170e3f8989"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "71905addd018976e0129e9ae44637af5b9315c33c6cd9d819b7a438ad0d64e62"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_linux_amd64.tar.gz"
    end
  end

  name "c3x"
  desc "Cloud cost estimation for Terraform & CloudFormation. No API key, no SaaS."
  homepage "https://c3x.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c3x"

  # No zap stanza required
end
