# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3x" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "5fff191e0a131eb75468cd27f364bc8898a88904ebe430a6dc3d086958135237"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "366a7da882daaf7d8f8ceafa2ba38847a18e976a191a02c7acd9d9f3cccd639f"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "28809fb8928e8eb21c5610e0c9f0a18ae17999752ac9784b5fe58f3b6a23acff"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "42fa6b42340582505df50f32d3d293b026f94394524d7d32f0439b6ce3128a80"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_linux_amd64.tar.gz"
    end
  end

  name "c3x"
  desc "Cloud cost estimation for Terraform & CloudFormation. No API key, no SaaS."
  homepage "https://c3x.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c3x"

  # No zap stanza required
end
