# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3x" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "2cb2d794e95b3c358315c71e9a0253d52cb167d0a96b7be316048d3a021e7041"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dba45988aa535b4067863ed5426aba94d97b1af46b6668a53ed855ec91d5f8b0"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d44eb1d240b6ba4e329bd9b3a99478dec8f9a76082af6f5ed170430414d7ca8"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "60a00eb21649313432d60c345750fbaae2d0d348653ad4875cadb93688e90902"
      url "https://github.com/c3xdev/c3x/releases/download/v#{version}/c3x_#{version}_linux_arm64.tar.gz"
    end
  end

  name "c3x"
  desc "Cloud cost estimation for Terraform & CloudFormation. No API key, no SaaS."
  homepage "https://c3x.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c3x"

  # No zap stanza required

end
